# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('current_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[(b'auto', b'Auto'), (b'enabled', b'Enabled'), (b'disabled', b'Disabled')], default=b'auto', max_length=16)),
                ('sitemap_item_id', models.CharField(editable=False, max_length=255, null=True)),
                ('sitemap_item_title', models.CharField(editable=False, max_length=255, null=True)),
                ('sitemap_item_status', models.CharField(choices=[(b'auto', b'Auto'), (b'enabled', b'Enabled'), (b'disabled', b'Disabled')], editable=False, max_length=16, null=True, verbose_name='Page Status')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.Menu')),
                ('my_parent', models.ForeignKey(blank=True, db_column=b'parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='navigation.MenuItem', verbose_name='Parent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(editable=False, max_length=255, verbose_name='Slug')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            managers=[
                ('current_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sitemap',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.Sitemap'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sitemap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='navigation.Sitemap'),
        ),
    ]
